import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";
import NavBar from "./NavBar";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistMono.variable}antialiased`}>
        <ThemeProvider attribute="class">
          <Theme
            accentColor="blue"
            scaling="105%"
            grayColor="sand"
            radius="small"
          >
            <NavBar />
            <main className="px-4">{children}</main>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
